# ── Подключаем тему и плагины ─────────────────────────────────────────────────
remote_theme: "mmistakes/minimal-mistakes@4.27.3"
plugins:
  - jekyll-include-cache   # требуется для кэша include_cached
  - jekyll-feed            # генерирует feed.xml
  - jekyll-seo-tag         # мета-теги для SEO
  - jekyll-sitemap         # sitemap.xml

# ── Основные параметры сайта ───────────────────────────────────────────────────
title: "Bogdan Minko"
description: "AI Engineer Portfolio and Blog"
lang: "en"

# ── Скин темы ───────────────────────────────────────────────────────────────────
minimal_mistakes_skin: "dark"

# ── Настройки по умолчанию ──────────────────────────────────────────────────────
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: wide
      author_profile: true
  - scope:
      path: ""
    values:
      layout: wide
      author_profile: true

# ── Информация об авторе ────────────────────────────────────────────────────────
author:
  name: "Bogdan Minko"
  avatar: "/assets/avatar.jpg"    # опционально
  bio: "AI Engineer, AI Sec Engineer."
  links:
    github:   "https://github.com/bogdanminko"
    linkedin: "https://linkedin.com/in/bogdan-minko-05a867322"
    medium:   "https://medium.com/@minkobogdan2001"
    habr:     "https://habr.com/ru/users/Bogdan_m01"

# ── Навигация ──────────────────────────────────────────────────────────────────
masthead_title: "Bogdan Minko"

# Главное меню
navigation:
  main:
    - title: "Projects" 
      url: /projects/
    - title: "Contact"
      url: /contact/

# ── Блог и пагинация ──────────────────────────────────────────────────────────
paginate: 5
paginate_path: "/page:num/"

# ── Настройки подсветки синтаксиса ──────────────────────────────────────────
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    default_lang: text
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# ── Пример настроек (по умолчанию в конфиге темы более 300 строк с комментариями!) ─
# Вы можете скопировать весь _config.yml из репозитория темы и удалить ненужное.
